server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/query_db
    username: query_user
    password: query_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: simple

  security:
    user:
      name: user
      password: password

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    com.nvbinhsoft.blog.query: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
